from commands.download import DownloadCommand
from commands.preprocess import PreprocessGBIFCommand, PreprocessZoneIDCommand, PreprocessZonalStatsCommand, PreprocessSplitDatasetCommand
from commands.train import TuneCommand, TrainCommand, EvaluateCommand
from commands.predict import PredictCommand
