from commands.download import DownloadCommand
from commands.preprocess import PreprocessGBIFCommand, PreprocessZoneIDCommand, PreprocessZonalStatsCommand, PreprocessSplitDatasetCommand
from commands.train import TuneCommand, TrainCommand
from commands.predict import PredictCommand
